@startuml
skinparam classAttributeIconSize 0
hide circle
hide empty members
skinparam linetype ortho

!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml

title Complete Pattern Structure Overview
package "io.github.valentinherrmann (framework: .levenshtein, example tests: .example.tests)" as AET {
    package "levenshtein" <<Framework>> {

        class WrapperProperty<T> {
            ~expected: T
            ~actual: T
            ~existence: Existence
        }

        abstract class Wrapper<T> {
            #name: WrapperProperty<String>
            #modifiers: WrapperProperty<String>
            #existence: Existence
            --
            +verifyExistence(throwAssertion: boolean)
            +getOverallExistence(): Existence
            #{abstract} findWithDeviation()
        }

        abstract class ClassWrapper<T> {
            -clazz: Class<T>
            #obj: T
            --
            +getClazz(): Class<T>
            +{abstract} getObj(forceNew, useByteBuddy): Object
            +getDynamicSubclassObj(...): Object
            +verifySuperClass()
            +verifyInterfaces()
        }

        class GenericClassWrapper<T>
        class AttributeWrapper<T,V>
        class MethodWrapper<T,R>
        class ConstructorWrapper<T>

        class StructuralLevenshtein {
            +{static} structuralTestFactory(...)
            +{static} structuralTestTemplate(...)
        }

        class Utils {
            +{static} levenshteinDistance(...)
            +{static} isNameWithinDeviation(...)
            +{static} saveCast(...)
        }

        ClassWrapper --|> Wrapper
        GenericClassWrapper --|> ClassWrapper
        AttributeWrapper --|> Wrapper
        MethodWrapper --|> Wrapper
        ConstructorWrapper --|> Wrapper

        Wrapper *-- WrapperProperty
    }

    package "wrappers" <<Test Implementation>> {
        class DrivableWrapper
        class AbstrWrapper
        class CarWrapper

        DrivableWrapper --|> ClassWrapper
        AbstrWrapper --|> ClassWrapper
        CarWrapper --|> ClassWrapper

        CarWrapper ..> AbstrWrapper : superClass
        CarWrapper ..> DrivableWrapper : interface
    }
}

@enduml

